add Person, Student and Teacher classes
disc3110/school-library-OPP-ruby pull request #1
Opened 2022-02-28 15:22 UTC by disc3110

added classes for Person and inheritance classes for Student and Teacher

2022-02-28 15:55 UTC, mikethreels requested changes
Hi Diego, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-28 15:55 UTC, mikethreels commented on lib/student.rb
> +  def initialize(age, name, parent_permission, classroom: nil)
- [x] the `name` and `parent_permission` arguments should have a default value.

2022-02-28 15:55 UTC, mikethreels commented on lib/teacher.rb
> +  def initialize(age, name, parent_permission, specialization)
- [x] the `name` and `parent_permission` arguments should have a default value.

2022-03-01 00:26 UTC, omar-labana approved these changes
# **Approved ✔️**

Hi @disc3110,

Congratulations on completing this project! 👏🏼 🎉

You have correctly implemented all of the requirements📃 correctly and without any errors⚠️ or bugs🪲.

Cheers and good luck in your next milestones! 🍀

Feel free to leave any questions or comments in the PR thread(don't forget to tag me 😄) if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-01 03:02 UTC, merged